// Generated from bebop.config.ts. Do not edit this file.
export const bebopAdminManifest = {
  "collections": {
    "media": {
      "slug": "media",
      "labels": {
        "singular": "Media",
        "plural": "Media"
      },
      "fields": [
        {
          "name": "alt",
          "storageName": "alt",
          "label": "Alt",
          "kind": "text",
          "required": false
        },
        {
          "name": "filename",
          "storageName": "filename",
          "label": "Filename",
          "kind": "text",
          "required": true,
          "generated": true
        },
        {
          "name": "mimeType",
          "storageName": "mimeType",
          "label": "Mime Type",
          "kind": "text",
          "required": true,
          "generated": true
        },
        {
          "name": "filesize",
          "storageName": "filesize",
          "label": "Filesize",
          "kind": "integer",
          "required": true,
          "generated": true
        }
      ],
      "timestamps": true,
      "useAsTitle": "filename",
      "defaultColumns": [
        "filename",
        "mimeType",
        "filesize"
      ],
      "listSearchableFields": [
        "filename"
      ],
      "upload": {
        "mimeTypes": [
          "image/*"
        ],
        "maxFileSize": 20971520
      }
    },
    "workspaces": {
      "slug": "workspaces",
      "labels": {
        "singular": "Workspace",
        "plural": "Workspaces"
      },
      "fields": [
        {
          "name": "name",
          "storageName": "name",
          "label": "Name",
          "kind": "text",
          "required": true
        },
        {
          "name": "slug",
          "storageName": "slug",
          "label": "Slug",
          "kind": "text",
          "required": true
        },
        {
          "name": "members",
          "label": "Members",
          "kind": "join",
          "required": false,
          "collection": "workspaceMemberships",
          "on": "workspace",
          "admin": {
            "defaultColumns": [
              "user",
              "workspace",
              "role",
              "status"
            ]
          }
        }
      ],
      "timestamps": true,
      "useAsTitle": "name",
      "defaultColumns": [
        "name",
        "slug"
      ],
      "listSearchableFields": [
        "name",
        "slug"
      ]
    },
    "workspaceMemberships": {
      "slug": "workspaceMemberships",
      "labels": {
        "singular": "Workspace Membership",
        "plural": "Workspace Memberships"
      },
      "fields": [
        {
          "name": "workspace",
          "storageName": "workspaceId",
          "label": "Workspace",
          "kind": "relation",
          "required": true,
          "relationTo": "workspaces"
        },
        {
          "name": "user",
          "storageName": "userId",
          "label": "User",
          "kind": "relation",
          "required": true,
          "relationTo": "better_auth_user"
        },
        {
          "name": "role",
          "storageName": "role",
          "label": "Role",
          "kind": "select",
          "required": true,
          "options": [
            "admin",
            "manager",
            "member",
            "guest"
          ],
          "optionLabels": {
            "admin": "Admin",
            "manager": "Manager",
            "member": "Member",
            "guest": "Guest"
          }
        },
        {
          "name": "status",
          "storageName": "status",
          "label": "Status",
          "kind": "select",
          "required": true,
          "options": [
            "active",
            "pending",
            "deactivated"
          ],
          "optionLabels": {
            "active": "Active",
            "pending": "Pending",
            "deactivated": "Deactivated"
          }
        }
      ],
      "timestamps": true,
      "useAsTitle": "user",
      "defaultColumns": [
        "user",
        "workspace",
        "role",
        "status"
      ],
      "listSearchableFields": [
        "user"
      ]
    },
    "tasks": {
      "slug": "tasks",
      "labels": {
        "singular": "Task",
        "plural": "Tasks"
      },
      "fields": [
        {
          "name": "name",
          "storageName": "name",
          "label": "Name",
          "kind": "text",
          "required": true
        },
        {
          "name": "workspace",
          "storageName": "workspaceId",
          "label": "Workspace",
          "kind": "relation",
          "required": false,
          "admin": {
            "position": "sidebar"
          },
          "relationTo": "workspaces"
        },
        {
          "name": "content",
          "storageName": "content",
          "label": "Content",
          "kind": "text",
          "required": false,
          "admin": {
            "input": "textarea"
          }
        },
        {
          "name": "image",
          "storageName": "imageId",
          "label": "Image",
          "kind": "upload",
          "required": false,
          "relationTo": "media"
        },
        {
          "name": "priority",
          "storageName": "priority",
          "label": "Priority",
          "kind": "select",
          "required": false,
          "admin": {
            "position": "sidebar"
          },
          "options": [
            "low",
            "medium",
            "high",
            "urgent"
          ],
          "optionLabels": {
            "low": "Low",
            "medium": "Medium",
            "high": "High",
            "urgent": "Urgent"
          }
        },
        {
          "name": "parentTask",
          "storageName": "parentTaskId",
          "label": "Parent Task",
          "kind": "relation",
          "required": false,
          "admin": {
            "position": "sidebar"
          },
          "relationTo": "tasks"
        },
        {
          "name": "author",
          "storageName": "authorId",
          "label": "Author",
          "kind": "relation",
          "required": true,
          "admin": {
            "position": "sidebar"
          },
          "relationTo": "better_auth_user"
        },
        {
          "name": "status",
          "storageName": "status",
          "label": "Status",
          "kind": "select",
          "required": false,
          "admin": {
            "position": "sidebar"
          },
          "options": [
            "backlog",
            "todo",
            "in-progress",
            "in-review",
            "done"
          ],
          "optionLabels": {
            "backlog": "Backlog",
            "todo": "To Do",
            "in-progress": "In Progress",
            "in-review": "In Review",
            "done": "Done"
          }
        },
        {
          "name": "assignee",
          "storageName": "assigneeId",
          "label": "Assignee",
          "kind": "relation",
          "required": false,
          "admin": {
            "position": "sidebar"
          },
          "relationTo": "better_auth_user"
        },
        {
          "name": "dueAt",
          "storageName": "dueAt",
          "label": "Due At",
          "kind": "date",
          "required": false,
          "admin": {
            "position": "sidebar",
            "date": {
              "pickerAppearance": "dayAndTime"
            }
          }
        },
        {
          "name": "archivedAt",
          "storageName": "archivedAt",
          "label": "Archived At",
          "kind": "date",
          "required": false,
          "admin": {
            "position": "sidebar",
            "date": {
              "pickerAppearance": "dayAndTime"
            }
          }
        }
      ],
      "timestamps": true,
      "useAsTitle": "name",
      "defaultColumns": [
        "name",
        "workspace",
        "status",
        "assignee",
        "dueAt"
      ],
      "listSearchableFields": [
        "name",
        "content"
      ]
    }
  }
} as const;
