// Generated from bebop.config.ts. Do not edit this file.
import { schema as s } from "jazz-tools";
import { createBebopBetterAuth } from "@bebopdev/core/server";
import bebopConfig from "./bebop.config.js";

export const auth = createBebopBetterAuth({
  config: bebopConfig,
  baseURL: process.env.BETTER_AUTH_URL ?? "http://127.0.0.1:5173",
  secret: process.env.BETTER_AUTH_SECRET ?? "bebop-schema-generation-placeholder-secret",
  jazz: {
    db: async () => { throw new Error("Better Auth schema generation cannot query the database."); },
    schema: s.defineApp({}).wasmSchema,
  },
});
