// Generated from bebop.config.ts. Do not edit this file.
export const bebopAdminManifest = {
  "collections": {
    "posts": {
      "slug": "posts",
      "label": "Posts",
      "fields": [
        {
          "name": "title",
          "storageName": "title",
          "label": "Title",
          "kind": "text",
          "required": true
        },
        {
          "name": "author",
          "storageName": "authorId",
          "label": "Author",
          "kind": "relation",
          "required": true,
          "relationTo": "better_auth_user"
        },
        {
          "name": "body",
          "storageName": "body",
          "label": "Body",
          "kind": "text",
          "required": false
        },
        {
          "name": "slug",
          "storageName": "slug",
          "label": "Slug",
          "kind": "text",
          "required": false
        },
        {
          "name": "publishedAt",
          "storageName": "publishedAt",
          "label": "Published At",
          "kind": "date",
          "required": false
        },
        {
          "name": "published",
          "storageName": "published",
          "label": "Published",
          "kind": "boolean",
          "required": false
        },
        {
          "name": "category",
          "storageName": "category",
          "label": "Category",
          "kind": "select",
          "required": false,
          "options": [
            "announcement",
            "guide",
            "story"
          ]
        }
      ],
      "timestamps": true,
      "useAsTitle": "title",
      "defaultColumns": [
        "title",
        "author",
        "published",
        "category"
      ],
      "listSearchableFields": [
        "title",
        "slug"
      ]
    },
    "legacyPosts": {
      "slug": "legacyPosts",
      "label": "Legacy posts",
      "fields": [
        {
          "name": "title",
          "storageName": "title",
          "label": "Title",
          "kind": "text",
          "required": true
        },
        {
          "name": "author",
          "storageName": "author",
          "label": "Author",
          "kind": "text",
          "required": true
        },
        {
          "name": "body",
          "storageName": "body",
          "label": "Body",
          "kind": "text",
          "required": false
        },
        {
          "name": "slug",
          "storageName": "slug",
          "label": "Slug",
          "kind": "text",
          "required": false
        },
        {
          "name": "publishedAt",
          "storageName": "publishedAt",
          "label": "Published At",
          "kind": "date",
          "required": false
        },
        {
          "name": "published",
          "storageName": "published",
          "label": "Published",
          "kind": "boolean",
          "required": false
        },
        {
          "name": "category",
          "storageName": "category",
          "label": "Category",
          "kind": "select",
          "required": false,
          "options": [
            "announcement",
            "guide",
            "story"
          ]
        }
      ],
      "timestamps": true,
      "useAsTitle": "title",
      "defaultColumns": [
        "title",
        "author",
        "published",
        "category"
      ],
      "listSearchableFields": [
        "title",
        "slug",
        "author"
      ]
    }
  }
} as const;
