// Generated by Bebop as Jazz's conventional schema.ts entry point.
// Bebop's generated schema is in bebop-generated-schema.ts.
// Schema fingerprint: 404f8fdf3f98ca8a1719c43f824dc952c553dae9a5a35b595e44e4e4028ca68c
export { app } from "./bebop-generated-schema.js";
