// Generated by Bebop as Jazz's conventional schema.ts entry point.
// Bebop's generated schema is in bebop-generated-schema.ts.
// Schema fingerprint: 90e6733e45a858489bcaee546e42aec241edd204b2f8f634359c8695f16f1388
export { app } from "./bebop-generated-schema.js";
