// Generated by Bebop as Jazz's conventional schema.ts entry point.
// Bebop's generated schema is in bebop-generated-schema.ts.
// Schema fingerprint: eeedcbfd3964c3894b2c8b42863c75aa7cec0cfe43f210cfb8d47f63482c7b7c
export { app } from "./bebop-generated-schema.js";
