// Generated by Bebop as Jazz's conventional schema.ts entry point.
// Bebop's generated schema is in bebop-generated-schema.ts.
// Schema fingerprint: 38a4379057d89d0d8a94c2e6ef9bfa415805ebe5f7d794bfeca1fedde5b93eb3
export { app } from "./bebop-generated-schema.js";
