import type { BebopConfig, FieldDefinition } from "./bebop.ts";

const namePattern = /^[A-Za-z][A-Za-z0-9_]*$/;

export function normalizeConfig(config: BebopConfig) {
  validateConfig(config);
  return {
    auth: config.auth,
    collections: Object.entries(config.collections).map(([name, definition]) => {
      const fields = Object.entries(definition.fields).map(([fieldName, field]) => ({
        name: fieldName,
        storageName: field.kind === "relation" ? `${fieldName}Id` : fieldName,
        label: humanize(fieldName),
        kind: field.kind,
        required: Boolean(field.required),
        definition: field,
        ...(field.admin?.position ? { admin: { position: field.admin.position } } : {}),
        ...(field.kind === "select" ? { options: field.options } : {}),
        ...(field.kind === "relation" ? { relationTo: field.to } : {}),
      }));
      const fieldNames = fields.map((field) => field.name);
      const useAsTitle = definition.admin?.useAsTitle ?? (fieldNames.includes("title") ? "title" : undefined);
      return {
        name,
        fields,
        access: definition.access,
        admin: {
          label: definition.admin?.label ?? humanize(name),
          timestamps: definition.timestamps !== false,
          useAsTitle,
          defaultColumns: definition.admin?.defaultColumns ?? [
            ...(useAsTitle ? [useAsTitle] : []),
            ...fieldNames.filter((fieldName) => fieldName !== useAsTitle),
          ].slice(0, 4),
          listSearchableFields: definition.admin?.listSearchableFields ?? (useAsTitle ? [useAsTitle] : []),
        },
      };
    }),
  };
}

type NormalizedConfig = ReturnType<typeof normalizeConfig>;

function compileSchemaFromModel(model: NormalizedConfig): string {

  const tables = model.collections.map((collection) => {
    const columns: string[] = [];
    const relations: string[] = [];

    for (const field of collection.fields) {
      if (field.kind === "relation") {
        const columnName = field.storageName;
        const optional = field.required ? "" : ".optional()";
        columns.push(`${JSON.stringify(columnName)}: s.uuid()${optional}`);
        relations.push(
          `${JSON.stringify(field.name)}: s.rel(${JSON.stringify(field.relationTo)}, ${JSON.stringify(columnName)})`,
        );
        continue;
      }

      columns.push(
        `${JSON.stringify(field.name)}: ${compileFieldType(field.definition as Exclude<FieldDefinition, { kind: "relation" }>)}${field.required ? "" : ".optional()"}`,
      );
    }

    const relationObject = relations.length
      ? `{\n      ${relations.join(",\n      ")}\n    }`
      : "{}";

    return `  ${JSON.stringify(collection.name)}: s.table(\n    {\n      ${columns.join(",\n      ")}\n    },\n    ${relationObject},\n  )`;
  });

  const authImport = model.auth
    ? 'import { schema as betterAuthSchema } from "./schema-better-auth/schema.js";\n'
    : "";
  const entries = [...(model.auth ? ["  ...betterAuthSchema"] : []), ...tables];

  return `// Generated in bebop-generated-schema.ts from bebop.config.ts. Edit that file, then run bebop generate.\nimport { schema as s } from "jazz-tools";\n${authImport}\nconst schema = {\n${entries.join(",\n")}\n} as const;\n\ntype AppSchema = s.Schema<typeof schema>;\nexport const app: s.App<AppSchema> = s.defineApp(schema);\n`;
}

function compileAdminManifestFromModel(model: NormalizedConfig): string {
  const collections = model.collections.map((collection) => {
    const { label, timestamps, useAsTitle, defaultColumns, listSearchableFields } = collection.admin;
    const fields = collection.fields.map(({ name, storageName, label: fieldLabel, kind, required, ...rest }) => ({
      name, storageName, label: fieldLabel, kind, required,
      ...(rest.admin ? { admin: rest.admin } : {}),
      ...(rest.options ? { options: rest.options } : {}),
      ...(rest.relationTo ? { relationTo: rest.relationTo } : {}),
    }));
    return [collection.name, {
      slug: collection.name,
      label,
      fields,
      timestamps,
      ...(useAsTitle ? { useAsTitle } : {}),
      defaultColumns,
      listSearchableFields,
    }] as const;
  });

  return `// Generated from bebop.config.ts. Do not edit this file.\nexport const bebopAdminManifest = ${JSON.stringify({ collections: Object.fromEntries(collections) }, null, 2)} as const;\n`;
}

function compilePermissionsFromModel(
  model: NormalizedConfig,
  configModuleSpecifier = "./bebop.config.js",
): string {
  const hasAccessRules = model.collections.some((collection) => collection.access);
  const grants = model.collections
    .flatMap((collection) => {
      const collectionName = collection.name;
      const access = collection.access;
      if (!access) return [];
      const rules: string[] = [`  const ${collectionName}Access = bebopConfig.collections.${collectionName}.access;`];
      const operations = [
        ["read", "Read"],
        ["create", "Insert"],
        ["update", "Update"],
        ["delete", "Delete"],
      ] as const;
      for (const [accessOperation, jazzOperation] of operations) {
        if (!access[accessOperation]) continue;
        rules.push(
          `  if (${collectionName}Access?.${accessOperation}) {\n` +
            `    policy.${collectionName}.allow${jazzOperation}.where((row) => ${collectionName}Access.${accessOperation}!({ row, session, allOf, anyOf, exists, isCreator }) as never);\n` +
            `  }`,
        );
      }
      return rules;
    })
    .join("\n");

  const authImport = model.auth
    ? 'import { permissions as betterAuthPermissions } from "./schema-better-auth/schema.js";\n'
    : "";
  const configImport = hasAccessRules
    ? `import bebopConfig from ${JSON.stringify(configModuleSpecifier)};\n`
    : "";
  const existsHelper = hasAccessRules
    ? `\n  const exists = (collectionName: string, condition: Record<string, unknown>) => {\n` +
        `    const tablePolicy = (policy as unknown as Record<string, { exists: { where(input: Record<string, unknown>): unknown } }>)[collectionName];\n` +
        `    if (!tablePolicy) throw new Error(\`Unknown collection in access.exists(): \${collectionName}\`);\n` +
        `    return tablePolicy.exists.where(condition) as never;\n` +
        `  };\n`
    : "";
  const appPermissions = `const appPermissions = s.definePermissions(app, ({ policy, session, allOf, anyOf, isCreator }) => {${existsHelper}\n${grants}\n});`;

  return `// Generated from bebop.config.ts. Missing collection operations are denied by Jazz.\nimport { schema as s } from "jazz-tools";\nimport { app } from "./bebop-generated-schema.js";\n${authImport}${configImport}\n${appPermissions}\n${model.auth ? "export default { ...betterAuthPermissions, ...appPermissions };" : "export default appPermissions;"}\n`;
}

export function compileSchema(config: BebopConfig): string {
  return compileSchemaFromModel(normalizeConfig(config));
}

export function compileAdminManifest(config: BebopConfig): string {
  return compileAdminManifestFromModel(normalizeConfig(config));
}

export function compilePermissions(config: BebopConfig, configModuleSpecifier = "./bebop.config.js"): string {
  return compilePermissionsFromModel(normalizeConfig(config), configModuleSpecifier);
}

export function compileArtifacts(config: BebopConfig, configModuleSpecifier = "./bebop.config.js") {
  const model = normalizeConfig(config);
  return {
    schema: compileSchemaFromModel(model),
    adminManifest: compileAdminManifestFromModel(model),
    permissions: compilePermissionsFromModel(model, configModuleSpecifier),
    clientFactory: compileClientFactory(configModuleSpecifier),
  };
}

export function compileClientFactory(configModuleSpecifier = "./bebop.config.js"): string {
  return `// Generated from bebop.config.ts. Do not edit this file.\nimport { createBebopClient as createClient } from "@bebop/core";\nimport type { Db } from "jazz-tools";\nimport { app } from "./bebop-generated-schema.js";\nimport bebopConfig from ${JSON.stringify(configModuleSpecifier)};\n\nexport function createBebopClient(db: Db) {\n  return createClient({ app, config: bebopConfig, db });\n}\n`;
}

function compileFieldType(field: Exclude<FieldDefinition, { kind: "relation" }>): string {
  switch (field.kind) {
    case "text":
      return "s.string()";
    case "number":
      return "s.float()";
    case "integer":
      return "s.int()";
    case "boolean":
      return "s.boolean()";
    case "date":
      return "s.timestamp()";
    case "json":
      return "s.json()";
    case "select":
      return `s.enum(${field.options.map((option) => JSON.stringify(option)).join(", ")})`;
  }
}

function validateConfig(config: BebopConfig): void {
  if (!config.collections || Object.keys(config.collections).length === 0) {
    throw new Error("Bebop config must define at least one collection.");
  }

  const collectionNames = Object.keys(config.collections);

  if (config.auth && config.auth.provider !== "better-auth") {
    throw new Error(`Unsupported authentication provider "${config.auth.provider}".`);
  }

  for (const [collectionName, definition] of Object.entries(config.collections)) {
    if (!namePattern.test(collectionName)) {
      throw new Error(`Invalid collection name "${collectionName}". Use letters, numbers, and underscores.`);
    }

    if (config.auth && collectionName.startsWith("better_auth_")) {
      throw new Error(
        `Collection name "${collectionName}" uses the reserved Better Auth table prefix "better_auth_".`,
      );
    }

    if (!definition.fields || Object.keys(definition.fields).length === 0) {
      throw new Error(`Collection "${collectionName}" must define at least one field.`);
    }

    if (definition.timestamps === false) {
      throw new Error(
        `Collection "${collectionName}" cannot disable timestamps: Jazz records $createdAt and $updatedAt as built-in metadata.`,
      );
    }

    for (const operation of ["read", "create", "update", "delete"] as const) {
      const rule = definition.access?.[operation];
      if (rule !== undefined && typeof rule !== "function") {
        throw new Error(`Collection "${collectionName}" access.${operation} must be a callback.`);
      }
    }

    for (const hook of ["beforeChange", "afterChange", "beforeDelete", "afterDelete"] as const) {
      const callback = definition.hooks?.[hook];
      if (callback !== undefined && typeof callback !== "function") {
        throw new Error(`Collection "${collectionName}" hooks.${hook} must be a callback.`);
      }
    }

    if (definition.admin?.label !== undefined && !definition.admin.label.trim()) {
      throw new Error(`Collection "${collectionName}" admin label cannot be empty.`);
    }

    const storedNames = new Set<string>(["id"]);
    for (const [fieldName, field] of Object.entries(definition.fields)) {
      if (!namePattern.test(fieldName) || fieldName === "id") {
        throw new Error(`Invalid field name "${fieldName}" in collection "${collectionName}".`);
      }

      const storageName = field.kind === "relation" ? `${fieldName}Id` : fieldName;
      if (storedNames.has(storageName)) {
        throw new Error(`Field "${fieldName}" conflicts with another stored field in "${collectionName}".`);
      }
      storedNames.add(storageName);

      if (field.kind === "relation" && !collectionNames.includes(field.to) && !(config.auth?.provider === "better-auth" && field.to === "better_auth_user")) {
        throw new Error(`Relation "${collectionName}.${fieldName}" targets unknown collection "${field.to}".`);
      }

      if (field.kind === "select" && field.options.length === 0) {
        throw new Error(`Select field "${collectionName}.${fieldName}" must have at least one option.`);
      }
      if (field.admin?.position !== undefined && field.admin.position !== "main" && field.admin.position !== "sidebar") {
        throw new Error(`Field "${collectionName}.${fieldName}" admin.position must be "main" or "sidebar".`);
      }
    }

    const adminOptions = definition.admin;
    if (adminOptions?.useAsTitle && !Object.hasOwn(definition.fields, adminOptions.useAsTitle)) {
      throw new Error(`Collection "${collectionName}" admin.useAsTitle references unknown field "${adminOptions.useAsTitle}".`);
    }
    for (const fieldName of adminOptions?.defaultColumns ?? []) {
      if (!Object.hasOwn(definition.fields, fieldName)) {
        throw new Error(`Collection "${collectionName}" admin.defaultColumns references unknown field "${fieldName}".`);
      }
    }
    for (const fieldName of adminOptions?.listSearchableFields ?? []) {
      if (!Object.hasOwn(definition.fields, fieldName)) {
        throw new Error(`Collection "${collectionName}" admin.listSearchableFields references unknown field "${fieldName}".`);
      }
      if (definition.fields[fieldName].kind !== "text") {
        throw new Error(`Collection "${collectionName}" admin.listSearchableFields field "${fieldName}" must be text.`);
      }
    }
  }
}

function humanize(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (character) => character.toUpperCase());
}
