// Generated from bebop.config.ts. Do not edit this file.
export const bebopAdminManifest = {
  "collections": {
    "todos": {
      "slug": "todos",
      "labels": {
        "singular": "Todo",
        "plural": "Todos"
      },
      "fields": [
        {
          "name": "title",
          "storageName": "title",
          "label": "Title",
          "kind": "text",
          "required": true
        },
        {
          "name": "notes",
          "storageName": "notes",
          "label": "Notes",
          "kind": "text",
          "required": false,
          "admin": {
            "input": "textarea"
          }
        },
        {
          "name": "completed",
          "storageName": "completed",
          "label": "Completed",
          "kind": "boolean",
          "required": false,
          "admin": {
            "position": "sidebar"
          }
        },
        {
          "name": "dueAt",
          "storageName": "dueAt",
          "label": "Due At",
          "kind": "date",
          "required": false,
          "admin": {
            "position": "sidebar",
            "date": {
              "pickerAppearance": "dayAndTime"
            }
          }
        }
      ],
      "timestamps": true,
      "useAsTitle": "title",
      "defaultColumns": [
        "title",
        "completed",
        "dueAt"
      ],
      "listSearchableFields": [
        "title",
        "notes"
      ],
      "writeMode": "direct"
    }
  }
} as const;
