// Generated from bebop.config.ts. Do not edit this file.
import { createBebopClient as createClient } from "@bebop/core";
import type { Db } from "jazz-tools";
import { app } from "./bebop-generated-schema.js";
import bebopConfig from "./bebop.config.js";

export function createBebopClient(db: Db) {
  return createClient({ app, config: bebopConfig, db });
}
